<a href="https://colab.research.google.com/github/Saishna-Shamej/Data-science/blob/main/1NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_list = [1, 2, 3, 4]
my_list

[1, 2, 3, 4]

In [3]:
import numpy as np
np.array(my_list)


array([1, 2, 3, 4])

In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [7]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
np.linspace(0, 20, 3)

array([ 0., 10., 20.])

In [14]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.rand(3)

array([0.31226589, 0.20192065, 0.40975558])

In [18]:
np.random.rand(5,5)

array([[0.08404722, 0.13568612, 0.76691291, 0.25294342, 0.20429794],
       [0.11440105, 0.40406398, 0.76027807, 0.67371756, 0.67441875],
       [0.35391562, 0.01326503, 0.84539868, 0.22175433, 0.50842221],
       [0.95319037, 0.82224503, 0.81842351, 0.28474633, 0.10847436],
       [0.51276967, 0.59557788, 0.94797529, 0.38150781, 0.8828764 ]])

In [20]:
np.random.randn(3)

array([ 0.49195305, -0.3097391 , -0.45571305])

In [22]:
np.random.randn(5,4)

array([[-0.7075322 , -0.23907939, -0.78143652,  1.83745865],
       [ 0.68969254,  0.41625016, -2.83460975,  1.03087319],
       [-0.41902836, -1.47352049, -0.13444134,  0.55399189],
       [ 1.47369671,  1.15594152, -0.22333616, -0.63369555],
       [ 1.85709947, -0.55369341,  0.15932071,  0.12737492]])

In [23]:
np.random.randint(1,50)

12

In [24]:
np.random.randint(1,100)

62

In [25]:
np.random.randint(1,100,3)

array([62,  3, 10])

In [27]:
np.random.randint(1,50,4)

array([ 1, 30, 39, 43])

In [47]:
ar = np.arange(16)
ranar = np.random.randint(0,50,5)

In [48]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
ranar

array([ 1, 15, 22, 29, 44])

In [52]:
ar.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
ranar

array([ 1, 15, 22, 29, 44])

In [54]:
ranar.max()

44

In [55]:
ranar.min()

1

In [56]:

ranar.argmax()

4

In [57]:
ranar.argmin()

0

In [58]:
ar.shape

(16,)

In [61]:
ar.reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [62]:
ar.reshape(1,16).shape

(1, 16)

In [63]:
ar.reshape(16,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [64]:
ar.reshape(16,1).shape

(16, 1)

In [65]:
ar.dtype

dtype('int64')