<a href="https://colab.research.google.com/github/Saishna-Shamej/Data-science/blob/main/2NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[3]

3

In [ ]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [ ]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[0:5]= 50
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice = arr[0:7]
slice

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
slice[:]= 33
slice

array([33, 33, 33, 33, 33, 33, 33])

In [ ]:
arr

array([33, 33, 33, 33, 33, 33, 33,  7,  8,  9, 10])

In [ ]:
arrcopy= arr.copy()
arrcopy

array([33, 33, 33, 33, 33, 33, 33,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[2]

array([35, 40, 45])

In [ ]:
arr_2d[1][0]

20

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[2,:]

array([35, 40, 45])

In [ ]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr_length = arr2d.shape[1]


In [ ]:
arr_length

10

In [ ]:
for i in range(arr_length):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
arr2d[[4,6,7,8]]

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
import numpy as np
arr = np.arange(1,12)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [ ]:
bool_arr = arr>4
bool_arr



array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])